export const uiText = {
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      products: 'Products',
      track: 'Track',
      dashboard: 'Dashboard',
      profile: 'Profile',
    },
    common: {
      viewAll: 'View All',
      applyNow: 'Apply Now',
      inStock: 'In Stock',
      outOfStock: 'Out of Stock',
      adding: 'Adding',
      addToCart: 'Add to Cart',
      noResultsTitle: 'No results found',
      noResultsDescription: "Try adjusting your search terms to find what you're looking for.",
    },
    footer: {
      rights: 'All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms',
      help: 'Help',
      location: 'Gazi Online Location',
    },
    home: {
      searchPlaceholder: 'Explore civic services, products, or trackers...',
      popularServicesSubtitle: 'Popular Services',
      recentApplications: [
        { id: 'app-1', name: 'Income Certificate', ref: 'Ref: #CV-88219', status: 'COMPLETED' },
        { id: 'app-2', name: 'Trade License', ref: 'Ref: #CV-88432', status: 'PROCESSING' },
      ],
      offers: {
        badge: 'Limited Offer',
        title: '20% off on all\nCitizen Accessories',
        subtitle: 'Secure your digital life with premium protection.',
        button: 'Shop Now',
      },
      reviews: {
        subtitle: 'Tap the button to leave a review directly on Google Maps.',
        cta: 'Write a Review',
        unavailableTitle: 'Reviews unavailable',
        unavailableMessage: 'We could not load reviews right now. Please try again shortly.',
      },
      whyChoose: {
        items: [
          {
            title: 'Fast Service',
            text: 'Most applications processed within 24 hours with dedicated express queues.',
          },
          {
            title: 'Secure Payments',
            text: 'Military-grade encryption for every transaction you make on our platform.',
          },
          {
            title: '24/7 Support',
            text: 'Our team is always online to help you with your queries and document issues.',
          },
        ],
      },
      appCta: {
        titleLead: 'Always Connected.',
        titleAccent: 'Everywhere.',
        description: 'Download our app for faster processing and get real-time application trackers on your lockscreen.',
        button: 'Download App',
        whatsapp: 'WhatsApp Help',
      },
      productCategories: {
        accessories: 'Accessories',
        cards: 'Cards',
        documents: 'Documents',
        devices: 'Devices',
        general: 'Essentials',
      },
      productCard: {
        addedTitle: 'Added to cart',
        addedMessage: 'is ready in your cart.',
        failedTitle: 'Add to cart failed',
        failedMessage: 'Could not add this product right now.',
        viewDetails: 'View details for',
      },
      featuredProducts: {
        scrollLeft: 'Scroll featured products left',
        scrollRight: 'Scroll featured products right',
      },
    },
    pages: {
      services: {
        searchPlaceholder: 'Search for a service or scheme...',
        categories: {
          all: 'All',
          government: 'Government',
          finance: 'Finance',
          utility: 'Utility',
        },
        eyebrow: 'Popular Services',
        noResults: 'No services found',
      },
      products: {
        eyebrow: 'Shop Catalog',
        title: 'Explore Products',
        description: 'Browse your product catalog in one dedicated place without scrolling the home page.',
        searchPlaceholder: 'Search products by name or category...',
        all: 'All',
        sort: 'Sort',
        sortOptions: {
          featured: 'Featured',
          priceAsc: 'Price: Low to High',
          priceDesc: 'Price: High to Low',
          ratingDesc: 'Top Rated',
        },
        countSuffix: 'products',
        allCategories: 'All categories',
        filtered: 'Filtered',
        noResultsTitle: 'No matching products found',
        noResultsDescription: 'Try a different product name or category keyword.',
      },
      track: {
        title: 'Track Applications',
        description: 'Monitor the real-time status of your submissions.',
        liveStatus: 'Live Status',
        waitingForSync: 'Waiting for sync',
        lastSynced: 'Last synced',
        guestSaved: 'Guest orders saved on this device',
        availableWithoutSignIn: 'Tracking is available without sign in',
        searchPlaceholder: 'Search by name or reference...',
        refresh: 'Refresh',
        refreshing: 'Refreshing...',
        stats: {
          total: 'Total',
          completed: 'Completed',
          inProgress: 'In Progress',
          pending: 'Pending',
        },
        guestNotice: 'These guest orders are stored only on this device. Sign in before ordering if you want them to appear in your account dashboard.',
        noResults: 'No applications found',
        noResultsDescription: 'Track entries will appear here when you submit an application or search with a matching reference.',
        serviceRequest: 'Service Request',
        guest: 'Guest',
        statuses: {
          completed: 'Completed',
          processing: 'Processing',
          pending: 'Pending',
          rejected: 'Rejected',
        },
      },
      profile: {
        guestTitle: 'Sign in to view your profile',
        guestDescription: 'Personal information, linked accounts, notifications, and profile settings are available only after sign in.',
        guestButton: 'Sign In to Continue',
        citizen: 'Citizen',
        verified: 'Verified',
        admin: 'Admin',
        stats: {
          applications: 'Applications',
          active: 'Active',
          completed: 'Completed',
        },
        adminButton: 'Open Admin Dashboard',
        signOut: 'Sign Out',
        menuItems: [
          { icon: '👤', label: 'Personal Information', sublabel: 'Name, DOB, Address', color: 'bg-blue-50 dark:bg-blue-900/20' },
          { icon: '📱', label: 'Linked Accounts', sublabel: 'Aadhaar, PAN, Voter ID', color: 'bg-emerald-50 dark:bg-emerald-900/20' },
          { icon: '🔔', label: 'Notifications', sublabel: 'Manage alerts & preferences', color: 'bg-amber-50 dark:bg-amber-900/20' },
          { icon: '🔒', label: 'Security', sublabel: 'Password, 2FA, Sessions', color: 'bg-violet-50 dark:bg-violet-900/20' },
          { icon: '🌐', label: 'Language', sublabel: 'English, বাংলা', color: 'bg-cyan-50 dark:bg-cyan-900/20' },
          { icon: '❓', label: 'Help & Support', sublabel: 'FAQ, Contact us', color: 'bg-rose-50 dark:bg-rose-900/20' },
        ],
      },
    },
  },
  bn: {
    nav: {
      home: 'হোম',
      services: 'পরিষেবা',
      products: 'পণ্য',
      track: 'ট্র্যাক',
      dashboard: 'ড্যাশবোর্ড',
      profile: 'প্রোফাইল',
    },
    common: {
      viewAll: 'সব দেখুন',
      applyNow: 'এখনই আবেদন করুন',
      inStock: 'স্টকে আছে',
      outOfStock: 'স্টকে নেই',
      adding: 'যোগ হচ্ছে',
      addToCart: 'কার্টে যোগ করুন',
      noResultsTitle: 'কোন ফলাফল পাওয়া যায়নি',
      noResultsDescription: 'আপনি যা খুঁজছেন তা পেতে সার্চের শব্দ বদলে আবার চেষ্টা করুন।',
    },
    footer: {
      rights: 'সমস্ত অধিকার সংরক্ষিত।',
      privacy: 'গোপনীয়তা নীতি',
      terms: 'শর্তাবলী',
      help: 'সহায়তা',
      location: 'গাজি অনলাইন লোকেশন',
    },
    home: {
      searchPlaceholder: 'নাগরিক পরিষেবা, পণ্য বা ট্র্যাকার খুঁজুন...',
      popularServicesSubtitle: 'জনপ্রিয় পরিষেবা',
      recentApplications: [
        { id: 'app-1', name: 'ইনকাম সার্টিফিকেট', ref: 'রেফ: #CV-88219', status: 'COMPLETED' },
        { id: 'app-2', name: 'ট্রেড লাইসেন্স', ref: 'রেফ: #CV-88432', status: 'PROCESSING' },
      ],
      offers: {
        badge: 'সীমিত অফার',
        title: 'সব সিটিজেন অ্যাক্সেসরিজে\n২০% ছাড়',
        subtitle: 'প্রিমিয়াম সুরক্ষায় আপনার ডিজিটাল জীবনকে আরও নিরাপদ রাখুন।',
        button: 'এখনই কিনুন',
      },
      reviews: {
        subtitle: 'সরাসরি Google Maps-এ রিভিউ দিতে বাটনে ট্যাপ করুন।',
        cta: 'রিভিউ লিখুন',
        unavailableTitle: 'রিভিউ এখন দেখা যাচ্ছে না',
        unavailableMessage: 'এই মুহূর্তে রিভিউ লোড করা যায়নি। একটু পরে আবার চেষ্টা করুন।',
      },
      whyChoose: {
        items: [
          {
            title: 'দ্রুত পরিষেবা',
            text: 'অধিকাংশ আবেদন ২৪ ঘণ্টার মধ্যে আলাদা এক্সপ্রেস কিউ-এর মাধ্যমে প্রক্রিয়াকরণ করা হয়।',
          },
          {
            title: 'নিরাপদ পেমেন্ট',
            text: 'আপনার প্রতিটি লেনদেনের জন্য মিলিটারি-গ্রেড এনক্রিপশন ব্যবহার করা হয়।',
          },
          {
            title: '২৪/৭ সহায়তা',
            text: 'আপনার প্রশ্ন ও ডকুমেন্ট সমস্যায় আমাদের টিম সবসময় সহায়তার জন্য অনলাইনে থাকে।',
          },
        ],
      },
      appCta: {
        titleLead: 'সবসময় সংযুক্ত।',
        titleAccent: 'সব জায়গায়।',
        description: 'আরও দ্রুত প্রসেসিং আর লকস্ক্রিনে রিয়েল-টাইম অ্যাপ্লিকেশন ট্র্যাকার পেতে আমাদের অ্যাপ ডাউনলোড করুন।',
        button: 'অ্যাপ ডাউনলোড করুন',
        whatsapp: 'হোয়াটসঅ্যাপ সহায়তা',
      },
      productCategories: {
        accessories: 'অ্যাক্সেসরিজ',
        cards: 'কার্ড',
        documents: 'ডকুমেন্ট',
        devices: 'ডিভাইস',
        general: 'প্রয়োজনীয়',
      },
      productCard: {
        addedTitle: 'কার্টে যোগ হয়েছে',
        addedMessage: 'এখন আপনার কার্টে রয়েছে।',
        failedTitle: 'কার্টে যোগ করা যায়নি',
        failedMessage: 'এই মুহূর্তে পণ্যটি কার্টে যোগ করা যাচ্ছে না।',
        viewDetails: 'বিস্তারিত দেখুন',
      },
      featuredProducts: {
        scrollLeft: 'ফিচার্ড পণ্য বামে স্ক্রল করুন',
        scrollRight: 'ফিচার্ড পণ্য ডানে স্ক্রল করুন',
      },
    },
    pages: {
      services: {
        searchPlaceholder: 'কোন পরিষেবা বা স্কিম খুঁজছেন...',
        categories: {
          all: 'সব',
          government: 'সরকারি',
          finance: 'ফাইন্যান্স',
          utility: 'ইউটিলিটি',
        },
        eyebrow: 'জনপ্রিয় পরিষেবা',
        noResults: 'কোন পরিষেবা পাওয়া যায়নি',
      },
      products: {
        eyebrow: 'পণ্য তালিকা',
        title: 'পণ্য ঘুরে দেখুন',
        description: 'হোম পেজে স্ক্রল না করেই এক জায়গায় পুরো পণ্য তালিকা দেখুন।',
        searchPlaceholder: 'নাম বা ক্যাটাগরি দিয়ে পণ্য খুঁজুন...',
        all: 'সব',
        sort: 'সাজান',
        sortOptions: {
          featured: 'ফিচার্ড',
          priceAsc: 'দাম: কম থেকে বেশি',
          priceDesc: 'দাম: বেশি থেকে কম',
          ratingDesc: 'সর্বোচ্চ রেটেড',
        },
        countSuffix: 'টি পণ্য',
        allCategories: 'সব ক্যাটাগরি',
        filtered: 'ফিল্টার করা',
        noResultsTitle: 'মিলে এমন কোন পণ্য পাওয়া যায়নি',
        noResultsDescription: 'অন্য নাম বা ক্যাটাগরি লিখে আবার চেষ্টা করুন।',
      },
      track: {
        title: 'আবেদন ট্র্যাক করুন',
        description: 'আপনার জমা দেওয়া আবেদনের রিয়েল-টাইম স্ট্যাটাস দেখুন।',
        liveStatus: 'লাইভ স্ট্যাটাস',
        waitingForSync: 'সিঙ্কের অপেক্ষায়',
        lastSynced: 'সর্বশেষ সিঙ্ক',
        guestSaved: 'গেস্ট অর্ডার এই ডিভাইসেই সংরক্ষিত আছে',
        availableWithoutSignIn: 'সাইন ইন ছাড়াই ট্র্যাক করা যাবে',
        searchPlaceholder: 'নাম বা রেফারেন্স দিয়ে খুঁজুন...',
        refresh: 'রিফ্রেশ',
        refreshing: 'রিফ্রেশ হচ্ছে...',
        stats: {
          total: 'মোট',
          completed: 'সম্পন্ন',
          inProgress: 'চলমান',
          pending: 'অপেক্ষমান',
        },
        guestNotice: 'এই গেস্ট অর্ডারগুলো শুধু এই ডিভাইসেই সংরক্ষিত থাকে। অ্যাকাউন্ট ড্যাশবোর্ডে দেখতে চাইলে অর্ডারের আগে সাইন ইন করুন।',
        noResults: 'কোন আবেদন পাওয়া যায়নি',
        noResultsDescription: 'আপনি আবেদন জমা দিলে বা মিল থাকা রেফারেন্স খুঁজলে এখানে ট্র্যাকিং তথ্য দেখাবে।',
        serviceRequest: 'পরিষেবা অনুরোধ',
        guest: 'গেস্ট',
        statuses: {
          completed: 'সম্পন্ন',
          processing: 'প্রক্রিয়াধীন',
          pending: 'অপেক্ষমান',
          rejected: 'প্রত্যাখ্যাত',
        },
      },
      profile: {
        guestTitle: 'প্রোফাইল দেখতে সাইন ইন করুন',
        guestDescription: 'সাইন ইন করার পরেই ব্যক্তিগত তথ্য, লিঙ্কড অ্যাকাউন্ট, নোটিফিকেশন এবং প্রোফাইল সেটিংস দেখা যাবে।',
        guestButton: 'সাইন ইন করে এগিয়ে যান',
        citizen: 'নাগরিক',
        verified: 'ভেরিফায়েড',
        admin: 'অ্যাডমিন',
        stats: {
          applications: 'আবেদন',
          active: 'সক্রিয়',
          completed: 'সম্পন্ন',
        },
        adminButton: 'অ্যাডমিন ড্যাশবোর্ড খুলুন',
        signOut: 'সাইন আউট',
        menuItems: [
          { icon: '👤', label: 'ব্যক্তিগত তথ্য', sublabel: 'নাম, জন্মতারিখ, ঠিকানা', color: 'bg-blue-50 dark:bg-blue-900/20' },
          { icon: '📱', label: 'লিঙ্কড অ্যাকাউন্ট', sublabel: 'আধার, প্যান, ভোটার আইডি', color: 'bg-emerald-50 dark:bg-emerald-900/20' },
          { icon: '🔔', label: 'নোটিফিকেশন', sublabel: 'অ্যালার্ট ও পছন্দ নিয়ন্ত্রণ করুন', color: 'bg-amber-50 dark:bg-amber-900/20' },
          { icon: '🔒', label: 'নিরাপত্তা', sublabel: 'পাসওয়ার্ড, 2FA, সেশন', color: 'bg-violet-50 dark:bg-violet-900/20' },
          { icon: '🌐', label: 'ভাষা', sublabel: 'ইংরেজি, বাংলা', color: 'bg-cyan-50 dark:bg-cyan-900/20' },
          { icon: '❓', label: 'সহায়তা ও সাপোর্ট', sublabel: 'FAQ, যোগাযোগ', color: 'bg-rose-50 dark:bg-rose-900/20' },
        ],
      },
    },
  },
} as const;

export type Language = keyof typeof uiText;
export type UIText = (typeof uiText)[Language];
