import React, { useState, useCallback, useRef } from 'react'
import ReactDOM from 'react-dom'
import { useDropzone } from 'react-dropzone'
import { PDFDocument, rgb } from 'pdf-lib'
import { smartCrop, magicFilter } from '../lib/imageProcessing'
import ImageEditor from './ImageEditor'

// ── Types ────────────────────────────────────────────────────────────────────
interface CardFile {
  file: File
  preview: string       // current visible preview (may be cropped/filtered)
  original: string      // original objectURL
  isCropped: boolean
  isFiltered: boolean
}

// ── PDF generation ────────────────────────────────────────────────────────────
function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((res, rej) => {
    const img = new Image()
    img.onload = () => res(img)
    img.onerror = rej
    img.crossOrigin = 'anonymous'
    img.src = src
  })
}

async function previewToJpegBytes(src: string): Promise<Uint8Array> {
  const img = await loadImage(src)
  const c = document.createElement('canvas')
  c.width = img.naturalWidth; c.height = img.naturalHeight
  c.getContext('2d')!.drawImage(img, 0, 0)
  const b64 = c.toDataURL('image/jpeg', 0.92).split(',')[1]
  return Uint8Array.from(atob(b64), ch => ch.charCodeAt(0))
}

async function buildA4PDF(front: CardFile | null, back: CardFile | null, cardType: 'voter' | 'aadhar' | 'passport'): Promise<Uint8Array> {
  const pdf = await PDFDocument.create()
  const A4W = 595.28, A4H = 841.89
  const page = pdf.addPage([A4W, A4H])
  const margin = 36

  // CM to points (1cm = 28.346 pts)
  const CM = 28.346
  let cardW = cardType === 'voter' ? 5.8 * CM : cardType === 'passport' ? 3.5 * CM : 8.56 * CM
  let cardH = cardType === 'voter' ? 8.5 * CM : cardType === 'passport' ? 4.5 * CM : 5.4 * CM

  const drawCard = async (cf: CardFile, yPos: number) => {
    const bytes = await previewToJpegBytes(cf.preview)
    const embedded = await pdf.embedJpg(bytes)
    const x = (A4W - cardW) / 2
    page.drawImage(embedded, { x, y: yPos, width: cardW, height: cardH })
  }

  const both = front && back
  if (both) {
    const gap = 140
    const totalH = cardH * 2 + gap
    const startY = (A4H + totalH) / 2 - cardH // top card Y
    await drawCard(front!, startY)
    await drawCard(back!, startY - cardH - gap)
  } else if (front || back) {
    const cf = (front || back)!
    const startY = (A4H + cardH) / 2 - cardH
    await drawCard(cf, startY)
  }

  // Footer
  page.drawText('Generated by: ID Card Scanner Pro', {
    x: margin, y: 18, size: 8, color: rgb(0.5, 0.5, 0.5),
  })

  return pdf.save()
}

async function buildA4Image(front: CardFile | null, back: CardFile | null, cardType: 'voter' | 'aadhar' | 'passport', mime: 'image/png' | 'image/jpeg'): Promise<void> {
  // A4 at 96dpi ≈ 794×1123px
  const W = 794, H = 1123
  const c = document.createElement('canvas')
  c.width = W; c.height = H
  const ctx = c.getContext('2d')!
  ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, W, H)

  // 1 cm ≈ 37.8 pixels at 96dpi
  const PX_CM = 37.8
  let cardW = cardType === 'voter' ? 5.8 * PX_CM : cardType === 'passport' ? 3.5 * PX_CM : 8.56 * PX_CM
  let cardH = cardType === 'voter' ? 8.5 * PX_CM : cardType === 'passport' ? 4.5 * PX_CM : 5.4 * PX_CM

  const drawCard = async (cf: CardFile, yTop: number) => {
    const img = await loadImage(cf.preview)
    ctx.drawImage(img, (W - cardW) / 2, yTop, cardW, cardH)
  }

  const both = front && back
  if (both) {
    const gap = 140
    const totalH = cardH * 2 + gap
    const startY = (H - totalH) / 2
    await drawCard(front!, startY)
    await drawCard(back!, startY + cardH + gap)
  } else if (front || back) {
    const cf = (front || back)!
    const startY = (H - cardH) / 2
    await drawCard(cf, startY)
  }

  ctx.fillStyle = '#888'
  ctx.font = '14px Arial'
  ctx.fillText('Generated by: ID Card Scanner Pro', 36, H - 24)

  c.toBlob(blob => {
    if (!blob) return
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `${cardType}-card-a4.${mime === 'image/png' ? 'png' : 'jpg'}`
    a.click(); URL.revokeObjectURL(url)
  }, mime, 0.93)
}

// ── CardDropZone ──────────────────────────────────────────────────────────────
const UploadIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className="w-10 h-10 text-gray-400">
    <rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="8.5" cy="10.5" r="1.5"/>
    <path strokeLinecap="round" d="M21 15l-5-5L5 21"/>
  </svg>
)

const CardDropZone: React.FC<{
  side: 'front' | 'back'
  card: CardFile | null
  onFile: (f: File) => void
  onRemove: () => void
  onMagicFilter: () => void
  onManualCrop: () => void
  processing: string
}> = ({ side, card, onFile, onRemove, onMagicFilter, onManualCrop, processing }) => {
  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop: accepted => { if (accepted[0]) onFile(accepted[0]) },
    accept: { 'image/jpeg': ['.jpg', '.jpeg'], 'image/png': ['.png'] },
    maxFiles: 1, multiple: false,
  })
  const label = side === 'front' ? 'Front' : 'Back'
  const busy = processing !== ''

  return (
    <div className="flex flex-col">
      <div className="flex items-center gap-1.5 mb-2">
        <div className="w-1 h-4 bg-blue-600 rounded-full"/>
        <span className="text-sm font-bold text-gray-800">ID Card {label} Side</span>
      </div>

      <div {...getRootProps()} className={`border-2 border-dashed rounded-lg flex flex-col items-center justify-center cursor-pointer transition-all min-h-[152px] relative overflow-hidden ${
        isDragActive ? 'border-blue-400 bg-blue-50'
        : card ? 'border-gray-200 bg-gray-50'
        : 'border-gray-300 bg-white hover:border-blue-400 hover:bg-blue-50/30'
      }`}>
        <input {...getInputProps()}/>
        {card ? (
          <>
            <img src={card.preview} alt={label} className="w-full max-h-[148px] object-contain"/>
            <button onClick={e => { e.stopPropagation(); onRemove() }}
              className="absolute top-1.5 right-1.5 w-6 h-6 bg-red-500 hover:bg-red-600 text-white rounded-full flex items-center justify-center text-sm font-bold">×</button>
            {card.isCropped && <span className="absolute top-1.5 left-1.5 px-1.5 py-0.5 bg-blue-600 text-white text-[9px] font-bold rounded">CROPPED</span>}
            {card.isFiltered && <span className="absolute bottom-1.5 left-1.5 px-1.5 py-0.5 bg-purple-600 text-white text-[9px] font-bold rounded">FILTERED</span>}
          </>
        ) : (
          <div className="flex flex-col items-center gap-2 p-4 text-center">
            <UploadIcon/>
            <p className="text-xs text-gray-500 font-medium">Tap or Drop {label} Image</p>
          </div>
        )}
      </div>

      <div className={`mt-2 py-1.5 px-3 rounded-full text-[11px] font-semibold text-center border ${
        card ? 'border-green-200 bg-green-50 text-green-700' : 'border-red-200 bg-red-50 text-red-500'
      }`}>
        {card ? `✓ ${card.file.name.length > 20 ? card.file.name.slice(0, 18) + '…' : card.file.name}` : 'No Image Uploaded'}
      </div>

      <div className="flex gap-1.5 mt-2">
        <button onClick={onManualCrop} disabled={!card || busy}
          className="flex-1 flex items-center justify-center gap-1 py-1.5 rounded border border-blue-300 bg-blue-50 text-[10px] font-bold text-blue-700 hover:bg-blue-100 disabled:opacity-40 disabled:cursor-not-allowed transition-colors">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-3 h-3">
            <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15"/>
          </svg>
          ✂️ Manual Crop & Rotate
        </button>
        <button onClick={onMagicFilter} disabled={!card || busy}
          className="flex-1 flex items-center justify-center gap-1 py-1.5 rounded border border-gray-300 text-[10px] font-semibold text-gray-600 hover:bg-purple-50 hover:border-purple-400 hover:text-purple-600 disabled:opacity-40 disabled:cursor-not-allowed transition-colors">
          {processing === 'filter'
            ? <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>
            : <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-3 h-3"><path strokeLinecap="round" strokeLinejoin="round" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>}
          Magic Filter
        </button>
      </div>
    </div>
  )
}

// ── Main Modal ────────────────────────────────────────────────────────────────
const IDCardScanModal: React.FC<{ onClose: () => void, initialType?: 'voter' | 'aadhar' | 'passport' }> = ({ onClose, initialType }) => {
  const [front, setFront] = useState<CardFile | null>(null)
  const [back,  setBack]  = useState<CardFile | null>(null)
  const [frontProc, setFrontProc] = useState('')
  const [backProc,  setBackProc]  = useState('')
  const [cardType, setCardType] = useState<'voter' | 'aadhar' | 'passport'>(initialType || 'voter')
  const [isExporting, setIsExporting] = useState(false)
  const [err, setErr] = useState('')
  const [editor, setEditor] = useState<{ side: 'front'|'back'; src: string } | null>(null)
  const overlayRef = useRef<HTMLDivElement>(null)
  const hasAny = front !== null || back !== null

  const makeCard = (file: File): CardFile => ({
    file, preview: URL.createObjectURL(file), original: URL.createObjectURL(file),
    isCropped: false, isFiltered: false,
  })

  const handleFile = useCallback(async (side: 'front' | 'back', file: File) => {
    const card = makeCard(file)
    const setCard = side === 'front' ? setFront : setBack
    const setProc = side === 'front' ? setFrontProc : setBackProc
    setCard(card)
    setErr('')

    // Auto-process: Smart Crop then Magic Filter
    setProc('processing')
    try {
      // 1. Smart Crop
      const cropped = await smartCrop(card.preview)
      // 2. Magic Filter
      const filtered = await magicFilter(cropped)
      setCard(prev => prev ? {
        ...prev,
        preview: filtered,
        isCropped: cropped !== card.preview,
        isFiltered: true
      } : null)
    } catch (e) {
      console.warn('Auto-processing failed', e)
    } finally {
      setProc('')
    }
  }, [])

  const handleRemove = useCallback((side: 'front' | 'back') => {
    if (side === 'front') setFront(prev => { if (prev) { URL.revokeObjectURL(prev.preview); URL.revokeObjectURL(prev.original) }; return null })
    else                  setBack(prev  => { if (prev) { URL.revokeObjectURL(prev.preview); URL.revokeObjectURL(prev.original) }; return null })
  }, [])

  const openEditor = useCallback((side: 'front' | 'back') => {
    const card = side === 'front' ? front : back
    if (!card) return
    setEditor({ side, src: card.preview })
  }, [front, back])

  const applyEdit = useCallback((dataUrl: string) => {
    if (!editor) return
    const setCard = editor.side === 'front' ? setFront : setBack
    setCard(prev => prev ? { ...prev, preview: dataUrl, isCropped: true } : null)
    setEditor(null)
  }, [editor])

  const applyMagicFilter = async (side: 'front' | 'back') => {
    const card = side === 'front' ? front : back
    if (!card) return
    const setProc = side === 'front' ? setFrontProc : setBackProc
    const setCard = side === 'front' ? setFront : setBack
    setProc('filter')
    try {
      const filtered = await magicFilter(card.preview)
      setCard(prev => prev ? { ...prev, preview: filtered, isFiltered: true } : null)
    } catch { setErr('Magic Filter failed. Try again.') }
    finally { setProc('') }
  }

  const handleExport = async (type: 'png' | 'jpg' | 'pdf' | 'print') => {
    if (!hasAny) return
    setIsExporting(true); setErr('')
    try {
      if (type === 'pdf' || type === 'print') {
        const bytes = await buildA4PDF(front, back, cardType)
        const blob = new Blob([bytes as any], { type: 'application/pdf' })
        const url = URL.createObjectURL(blob)
        if (type === 'print') {
          const win = window.open(url, '_blank')
          win?.addEventListener('load', () => win.print())
        } else {
          const a = document.createElement('a'); a.href = url; a.download = `${cardType}-card-a4.pdf`; a.click()
        }
        setTimeout(() => URL.revokeObjectURL(url), 60000)
      } else {
        await buildA4Image(front, back, cardType, type === 'png' ? 'image/png' : 'image/jpeg')
      }
    } catch (e) { console.error(e); setErr('Export failed. Please try again.') }
    finally { setIsExporting(false) }
  }

  React.useEffect(() => {
    const h = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', h); return () => window.removeEventListener('keydown', h)
  }, [onClose])

  React.useEffect(() => {
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = '' }
  }, [])

  const Spin = () => (
    <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
    </svg>
  )

  const modal = (
    <div
      ref={overlayRef}
      onClick={e => { if (e.target === overlayRef.current) onClose() }}
      className="fixed inset-0 z-[9999] flex items-center justify-center p-3 sm:p-6"
      style={{ background: 'rgba(0,0,0,0.72)', backdropFilter: 'blur(4px)' }}
    >
      <div
        className="relative w-full max-w-xl bg-white rounded-2xl shadow-2xl"
        style={{ maxHeight: '92vh', overflowY: 'auto' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Close */}
        <button onClick={onClose}
          className="absolute top-3 right-3 z-20 w-7 h-7 bg-red-500 hover:bg-red-600 text-white rounded-full flex items-center justify-center text-base font-bold transition-colors shadow"
          aria-label="Close">×</button>

        {/* Header */}
        <div className="flex items-center gap-3 px-5 pt-4 pb-3 border-b border-gray-100">
          <svg viewBox="0 0 72 52" fill="none" className="w-16 h-12 shrink-0">
            <rect x="1" y="1" width="70" height="50" rx="5" fill="#fff" stroke="#ddd" strokeWidth="1.5"/>
            <rect x="7" y="7" width="22" height="16" rx="2" fill="#e8f0fe"/>
            <circle cx="18" cy="13" r="4.5" fill="#4285f4"/>
            <path d="M11 23a7 7 0 0114 0" fill="#4285f4"/>
            <rect x="34" y="9" width="30" height="3" rx="1.5" fill="#4285f4"/>
            <rect x="34" y="16" width="22" height="2.5" rx="1.25" fill="#ddd"/>
            <rect x="34" y="21" width="17" height="2.5" rx="1.25" fill="#ddd"/>
            <rect x="48" y="1" width="22" height="16" rx="3" fill="#db4437"/>
            <text x="51" y="13" fontSize="7" fontWeight="bold" fill="white">PDF</text>
          </svg>
          <div className="flex-1 min-w-0">
            <h2 className="text-lg font-black text-blue-600 leading-tight">ID Card Scan To Pdf</h2>
            <p className="text-[11px] text-gray-500 mt-0.5">100% Free • Secure • ID Card A4 Pdf Print Ready</p>
          </div>
          <button
            onClick={() => {
              navigator.clipboard.writeText(window.location.href)
              setErr('Link copied to clipboard!')
              setTimeout(() => setErr(''), 2000)
            }}
            className="shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-purple-600 hover:bg-purple-700 text-white text-[11px] font-bold transition-colors mr-7"
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-3 h-3">
              <path strokeLinecap="round" strokeLinejoin="round" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"/>
            </svg>
            Share Tool
          </button>
        </div>

        {/* Card Type Selection */}
        <div className="px-5 py-4 bg-gray-50 border-b border-gray-100">
          <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">Select ID Card Type:</p>
          <div className="flex gap-4">
            <label className={`flex-1 flex items-center gap-3 p-3 rounded-xl border-2 transition-all cursor-pointer ${
              cardType === 'voter' ? 'border-blue-500 bg-blue-50' : 'border-gray-200 bg-white hover:border-gray-300'
            }`}>
              <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center ${
                cardType === 'voter' ? 'border-blue-500' : 'border-gray-400'
              }`}>
                {cardType === 'voter' && <div className="w-2 h-2 rounded-full bg-blue-500"/>}
              </div>
              <input type="radio" name="cardType" className="hidden"
                checked={cardType === 'voter'} onChange={() => setCardType('voter')} />
              <div className="flex flex-col">
                <span className="text-sm font-bold text-gray-800">Voter Card</span>
                <span className="text-[10px] text-gray-500 font-medium">Standard Voter ID size</span>
              </div>
            </label>
            <label className={`flex-1 flex items-center gap-3 p-3 rounded-xl border-2 transition-all cursor-pointer ${
              cardType === 'aadhar' ? 'border-blue-500 bg-blue-50' : 'border-gray-200 bg-white hover:border-gray-300'
            }`}>
              <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center ${
                cardType === 'aadhar' ? 'border-blue-500' : 'border-gray-400'
              }`}>
                {cardType === 'aadhar' && <div className="w-2 h-2 rounded-full bg-blue-500"/>}
              </div>
              <input type="radio" name="cardType" className="hidden"
                checked={cardType === 'aadhar'} onChange={() => setCardType('aadhar')} />
              <div className="flex flex-col">
                <span className="text-sm font-bold text-gray-800">Aadhar Card</span>
                <span className="text-[10px] text-gray-500 font-medium">Standard Aadhar ID size</span>
              </div>
            </label>
            <label className={`flex-1 flex items-center gap-3 p-3 rounded-xl border-2 transition-all cursor-pointer ${
              cardType === 'passport' ? 'border-blue-500 bg-blue-50' : 'border-gray-200 bg-white hover:border-gray-300'
            }`}>
              <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center ${
                cardType === 'passport' ? 'border-blue-500' : 'border-gray-400'
              }`}>
                {cardType === 'passport' && <div className="w-2 h-2 rounded-full bg-blue-500"/>}
              </div>
              <input type="radio" name="cardType" className="hidden"
                checked={cardType === 'passport'} onChange={() => setCardType('passport')} />
              <div className="flex flex-col">
                <span className="text-sm font-bold text-gray-800">Passport</span>
                <span className="text-[10px] text-gray-500 font-medium">3.5cm x 4.5cm size</span>
              </div>
            </label>
          </div>
        </div>

        {/* Status */}
        <div className="mx-4 mt-3 px-4 py-2 rounded-lg bg-green-50 border border-green-200 text-center text-sm font-semibold text-green-700">
          ✅ {cardType === 'voter' ? 'Voter Card' : cardType === 'passport' ? 'Passport' : 'Aadhar Card'} Mode Ready.
        </div>

        {/* Instructions */}
        <div className="mx-4 mt-2 px-4 py-2 rounded-lg border border-amber-300 bg-amber-50 text-center text-[11px] text-gray-700">
          <span className="font-bold text-amber-700">How to use: </span>
          Capture <span className="font-bold text-blue-600">Front & Back</span> of card. Apply{' '}
          <span className="font-bold text-blue-500">✂️ Manual Crop & Rotate</span> to trim borders, use{' '}
          <span className="font-bold text-purple-600">Magic Filter</span> to enhance, then save.
        </div>

        {/* Two panels */}
        <div className="grid grid-cols-2 gap-4 px-4 py-4">
          <CardDropZone side="front" card={front}
            onFile={f => handleFile('front', f)} onRemove={() => handleRemove('front')}
            onMagicFilter={() => applyMagicFilter('front')}
            onManualCrop={() => openEditor('front')}
            processing={frontProc}/>
          <CardDropZone side="back" card={back}
            onFile={f => handleFile('back', f)} onRemove={() => handleRemove('back')}
            onMagicFilter={() => applyMagicFilter('back')}
            onManualCrop={() => openEditor('back')}
            processing={backProc}/>
        </div>

        {err && (
          <div className="mx-4 mb-2 px-4 py-2 rounded-lg bg-red-50 border border-red-200 text-sm text-red-600 font-semibold">⚠️ {err}</div>
        )}

        {/* Export buttons */}
        <div className="grid grid-cols-4 gap-2 px-4 pb-5 pt-1">
          {([
            { label: 'Save as A4 PNG',   type: 'png'   as const, bg: 'bg-green-500 hover:bg-green-600' },
            { label: 'Save as A4 JPG',   type: 'jpg'   as const, bg: 'bg-purple-600 hover:bg-purple-700' },
            { label: 'Save as A4 PDF',   type: 'pdf'   as const, bg: 'bg-red-500 hover:bg-red-600' },
            { label: 'Direct A4 Print',  type: 'print' as const, bg: 'bg-blue-600 hover:bg-blue-700' },
          ] as const).map(({ label, type, bg }) => (
            <button key={type} onClick={() => handleExport(type)}
              disabled={!hasAny || isExporting}
              className={`flex flex-col items-center justify-center gap-1 py-2.5 px-1 rounded-lg ${bg} disabled:opacity-40 disabled:cursor-not-allowed text-white text-[10px] font-black transition-colors shadow-sm`}>
              {isExporting ? <Spin/> : type === 'print' ? (
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} className="w-4 h-4">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5zm-3 0h.008v.008H15V10.5z"/>
                </svg>
              ) : (
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} className="w-4 h-4">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"/>
                </svg>
              )}
              {label}
            </button>
          ))}
        </div>
      </div>
    </div>
  )

  return (
    <>
      {ReactDOM.createPortal(modal, document.body)}
      {editor && (
        <ImageEditor
          src={editor.src}
          onApply={applyEdit}
          onClose={() => setEditor(null)}
        />
      )}
    </>
  )
}

export default IDCardScanModal
